# Generated by Django 4.1.3 on 2022-11-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('authentication', '0002_usermodel_age_alter_usermodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='key',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='authtoken.token'),
        ),
    ]
